# Generated by Django 3.0.6 on 2020-05-08 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tampil',
            old_name='first_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tampil',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='tampil',
            name='last_name',
        ),
        migrations.AddField(
            model_name='tampil',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
